apiVersion: v1
kind: Secret
metadata:
  name: price-predictor-secrets
  namespace: price-predictor
type: Opaque
data:
  # Database credentials (base64 encoded)
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # 'postgres' - CHANGE IN PRODUCTION
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9wcmljZV9wcmVkaWN0b3I=
  
  # Redis credentials
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=  # 'redis_password' - CHANGE IN PRODUCTION
  
  # API credentials
  API_SECRET_KEY: c3VwZXJfc2VjcmV0X2tleV9jaGFuZ2VfaW5fcHJvZHVjdGlvbg==
  
  # External API keys (add your actual keys)
  BREEZE_API_KEY: ""
  BREEZE_API_SECRET: ""
  ALPHA_VANTAGE_API_KEY: ""
